package com.mytubews.corbaclient;


/**
* MyTube/IdServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
*/

public interface IdServerOperations 
{
  String generateId (String fileName);
  boolean verifyId (String id);
} // interface IdServerOperations
