package com.mytubews.corbaclient;


/**
* MyTube/IdServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
*/

public interface IdServer extends IdServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdServer
