# Python stubs generated by omniidl from idserver.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"idserver.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"idserver.idl")


# interface IdServer
_0__GlobalIDL._d_IdServer = (omniORB.tcInternal.tv_objref, "IDL:IdServer:1.0", "IdServer")
omniORB.typeMapping["IDL:IdServer:1.0"] = _0__GlobalIDL._d_IdServer
_0__GlobalIDL.IdServer = omniORB.newEmptyClass()
class IdServer :
    _NP_RepositoryId = _0__GlobalIDL._d_IdServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.IdServer = IdServer
_0__GlobalIDL._tc_IdServer = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_IdServer)
omniORB.registerType(IdServer._NP_RepositoryId, _0__GlobalIDL._d_IdServer, _0__GlobalIDL._tc_IdServer)

# IdServer operations and attributes
IdServer._d_novaChave = ((), ((omniORB.tcInternal.tv_string,0), ), None)
IdServer._d_verificaChave = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)

# IdServer object reference
class _objref_IdServer (CORBA.Object):
    _NP_RepositoryId = IdServer._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def novaChave(self, *args):
        return _omnipy.invoke(self, "novaChave", _0__GlobalIDL.IdServer._d_novaChave, args)

    def verificaChave(self, *args):
        return _omnipy.invoke(self, "verificaChave", _0__GlobalIDL.IdServer._d_verificaChave, args)

    __methods__ = ["novaChave", "verificaChave"] + CORBA.Object.__methods__

omniORB.registerObjref(IdServer._NP_RepositoryId, _objref_IdServer)
_0__GlobalIDL._objref_IdServer = _objref_IdServer
del IdServer, _objref_IdServer

# IdServer skeleton
__name__ = "_GlobalIDL__POA"
class IdServer (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.IdServer._NP_RepositoryId


    _omni_op_d = {"novaChave": _0__GlobalIDL.IdServer._d_novaChave, "verificaChave": _0__GlobalIDL.IdServer._d_verificaChave}

IdServer._omni_skeleton = IdServer
_0__GlobalIDL__POA.IdServer = IdServer
omniORB.registerSkeleton(IdServer._NP_RepositoryId, IdServer)
del IdServer
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "idserver_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
