package projsd;
/**
* IdServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Quarta-feira, 11 de Dezembro de 2013 12h39min37s BRST
*/

public interface IdServer extends IdServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdServer
