package projsd;
/**
* IdServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Quarta-feira, 11 de Dezembro de 2013 12h39min37s BRST
*/

public interface IdServerOperations 
{
  String novaChave ();

  //retorna uma nova chave
  boolean verificaChave (String chave);
} // interface IdServerOperations
